version: '2.1'

services:
  servidor_html:
    image: servidor_html
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
    volumes:
      - "./public:/usr/src/app/public"